sudo: required

# setup services.
services:
  - docker

# setup test directives
before_install:
  - docker build -t kewlpack/react-test -f ./client/Dockerfile.dev ./client

# execute all tests
script:
  - docker run -e CI=true kewlpack/react-test npm test

# post test, setup build for each image.
after_success:
  - docker build -t kewlpack/multi-client ./client
  - docker build -t kewlpack/multi-nginx ./nginx
  - docker build -t kewlpack/multi-server ./server
  - docker build -t kewlpack/multi-worker ./worker
  # log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push kewlpack/multi-client
  - docker push kewlpack/multi-nginx
  - docker push kewlpack/multi-server
  - docker push kewlpack/multi-worker
# configure deployment
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-929428780540"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
